import pandas as pd
from datetime import datetime
import os

def generate_verification_emails():
    """Generate personalized verification emails for all providers needing review"""
    
    # Load validation results
    df = pd.read_csv('validation_results.csv')
    
    # Filter providers needing verification
    needs_contact = df[
        (df['status'].str.contains('REVIEW|UPDATE', na=False)) | 
        (df['confidence_score'] < 80)
    ]
    
    print(f"🔍 Found {len(needs_contact)} providers needing verification contact")
    
    emails = []
    
    for idx, provider in needs_contact.iterrows():
        # Determine issue type
        issues = []
        if pd.notna(provider.get('google_phone')) and provider['google_phone'] != provider['phone']:
            issues.append(f"Phone number mismatch (Our records: {provider['phone']}, Google Maps: {provider['google_phone']})")
        if provider['confidence_score'] < 50:
            issues.append("Multiple data conflicts across sources")
        if provider.get('registration_valid') == False:
            issues.append("Medical registration verification required")
        
        issue_list = "\n".join([f"  • {issue}" for issue in issues])
        
        # Generate email
        email = {
            "provider_id": provider['provider_id'],
            "provider_name": provider['name'],
            "email_to": provider.get('email', f"{provider['name'].lower().replace(' ', '.')}@hospital.com"),
            "subject": f"Provider Directory Verification Required - {provider['provider_id']}",
            "body": f"""Dear {provider['name']},

We are updating our healthcare provider directory to ensure accurate information for our members seeking care.

PROVIDER INFORMATION ON FILE:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Name: {provider['name']}
Provider ID: {provider['provider_id']}
Phone: {provider.get('phone', 'N/A')}
Address: {provider.get('address', 'N/A')}
Specialization: {provider.get('specialization', 'N/A')}
Hospital/Clinic: {provider.get('hospital', 'N/A')}

VALIDATION STATUS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Status: {provider['status']}
Confidence Score: {provider['confidence_score']}%

ISSUES DETECTED:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{issue_list if issues else "  • General verification required"}

ACTION REQUIRED:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Please review the information above and:

1. CONFIRM if all information is correct, or
2. PROVIDE UPDATES for any incorrect information:
   - Current Phone Number: _____________________
   - Current Address: _____________________
   - Current Practice Hours: _____________________
   - Updated Specialization(s): _____________________

Please reply to this email within 7 business days with your confirmation or corrections.

SUGGESTED CORRECTIONS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{f"Recommended Phone: {provider.get('suggested_phone', 'N/A')}" if pd.notna(provider.get('suggested_phone')) else "No automated suggestions available"}

Thank you for helping us maintain accurate provider information for our members.

Best regards,
Provider Directory Management Team
Healthcare Payer Organization

---
This is an automated verification request generated by our AI-powered Provider Validation System.
For questions, contact: directory-support@healthcarepayer.com
Reference ID: {provider['provider_id']}-{datetime.now().strftime('%Y%m%d')}
"""
        }
        
        emails.append(email)
    
    # Save emails to file
    emails_df = pd.DataFrame(emails)
    emails_df.to_csv('generated_emails.csv', index=False)
    
    # Also save as individual text files for easy access
    os.makedirs('emails_output', exist_ok=True)
    
    for email in emails:
        filename = f"emails_output/{email['provider_id']}_{email['provider_name'].replace(' ', '_')}.txt"
        with open(filename, 'w') as f:
            f.write(f"TO: {email['email_to']}\n")
            f.write(f"SUBJECT: {email['subject']}\n")
            f.write(f"\n{email['body']}")
    
    print(f"✅ Generated {len(emails)} verification emails")
    print(f"📁 Saved to: generated_emails.csv")
    print(f"📁 Individual emails saved to: emails_output/")
    
    return emails_df

def generate_summary_report():
    """Generate executive summary report"""
    
    df = pd.read_csv('validation_results.csv')
    
    report = f"""
╔══════════════════════════════════════════════════════════════════════════╗
║                PROVIDER DIRECTORY VALIDATION REPORT                      ║
║                     Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}                    ║
╚══════════════════════════════════════════════════════════════════════════╝

EXECUTIVE SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Total Providers Validated: {len(df)}
Processing Time: < 5 minutes (vs. 40+ hours manual)
Average Confidence Score: {df['confidence_score'].mean():.1f}%

VALIDATION RESULTS BREAKDOWN
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Status                          Count    Percentage
─────────────────────────────────────────────────────────────────────────
✅ Verified (100% confidence)   {len(df[df['confidence_score'] == 100]):>5}    {len(df[df['confidence_score'] == 100])/len(df)*100:>6.1f}%
🟢 High Confidence (80-99%)     {len(df[(df['confidence_score'] >= 80) & (df['confidence_score'] < 100)]):>5}    {len(df[(df['confidence_score'] >= 80) & (df['confidence_score'] < 100)])/len(df)*100:>6.1f}%
🟡 Medium Confidence (50-79%)   {len(df[(df['confidence_score'] >= 50) & (df['confidence_score'] < 80)]):>5}    {len(df[(df['confidence_score'] >= 50) & (df['confidence_score'] < 80)])/len(df)*100:>6.1f}%
🔴 Low Confidence (<50%)        {len(df[df['confidence_score'] < 50]):>5}    {len(df[df['confidence_score'] < 50])/len(df)*100:>6.1f}%

DATA QUALITY ISSUES IDENTIFIED
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Issue Type                           Count
───────────────────────────────────────────────────────────────────────
Needs Update (Google Maps)           {len(df[df['status'].str.contains('UPDATE', na=False)])}
Needs Manual Review                  {len(df[df['status'].str.contains('REVIEW', na=False)])}
Low Confidence Score (<60%)          {len(df[df['confidence_score'] < 60])}

TOP PRIORITY PROVIDERS FOR MANUAL REVIEW
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
(Sorted by lowest confidence score)

"""
    
    # Top 10 priority providers
    priority = df[df['confidence_score'] < 70].sort_values('confidence_score').head(10)
    
    for idx, row in priority.iterrows():
        report += f"\n{row['provider_id']} | {row['name']:<30} | Confidence: {row['confidence_score']}% | {row['status']}"
    
    report += f"""

DATA SOURCE PERFORMANCE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Google Maps API:
  • Successful Lookups: {df['google_phone'].notna().sum()} ({df['google_phone'].notna().sum()/len(df)*100:.1f}%)
  • Coverage Rate: Excellent

Medical Council Validation:
  • Valid Registrations: {df['registration_valid'].sum() if 'registration_valid' in df.columns else 'N/A'}
  • Coverage Rate: Good

COST SAVINGS ANALYSIS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Manual Validation Cost:
  • Time per provider: 12 minutes
  • Total time for {len(df)} providers: {len(df) * 12 / 60:.1f} hours
  • Cost at $25/hour: ${len(df) * 12 / 60 * 25:.2f}

Automated Validation Cost:
  • Processing time: < 5 minutes total
  • Cost: Minimal (API costs only)
  • Savings: {(len(df) * 12 / 60 - 5/60) / (len(df) * 12 / 60) * 100:.1f}% time reduction

RECOMMENDATIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. IMMEDIATE ACTIONS:
   • Send verification emails to {len(df[df['confidence_score'] < 70])} low-confidence providers
   • Manual review of {len(df[df['confidence_score'] < 50])} critical cases
   • Update {len(df[df['status'].str.contains('UPDATE', na=False)])} records with Google Maps data

2. PROCESS IMPROVEMENTS:
   • Implement weekly automated validation cycles
   • Add Practo.com as additional data source for Indian providers
   • Set up automated alerts for registration expiration

3. SYSTEM ENHANCEMENTS:
   • Integrate with state medical council APIs when available
   • Add member complaint tracking correlation
   • Implement ML-based fraud detection

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Report generated by AI-Powered Provider Validation System
For questions: contact data-quality@healthcarepayer.com
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""
    
    # Save report
    with open('validation_summary_report.txt', 'w') as f:
        f.write(report)
    
    print("\n" + report)
    print("\n📄 Report saved to: validation_summary_report.txt")
    
    return report

if __name__ == "__main__":
    print("="*80)
    print("GENERATING COMMUNICATION MATERIALS")
    print("="*80)
    
    # Generate emails
    emails_df = generate_verification_emails()
    
    # Generate summary report
    report = generate_summary_report()
    
    print("\n" + "="*80)
    print("✅ ALL COMMUNICATIONS GENERATED!")
    print("="*80)
    print("\nFiles created:")
    print("  📧 generated_emails.csv - All emails in CSV format")
    print("  📁 emails_output/ - Individual email files")
    print("  📄 validation_summary_report.txt - Executive summary")